Attempt to use matrix for swift jobs and added windows.

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -118,33 +118,42 @@ jobs:
       - name: Check git status
         uses: Brent-Tunnicliff/action-git-status@v1
 
-  swift-macos:
-    name: "swift (macOS)"
-    runs-on: macos-26
-    steps:
-      # List all environment variables to help with debugging possible issues.
-      - name: List environment variables
-        run: set
-      - uses: actions/checkout@v4
-      - name: Build package
-        run: swift build
-      - name: Build tests
-        run: swift build --build-tests
-      - name: Run tests
-        run: swift test --xunit-output .build/report
-      - name: Upload test results
-        if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: test-macOS-swift.zip
-          path: .build/report-swift-testing
-          if-no-files-found: error
-      - name: Check git status
-        uses: Brent-Tunnicliff/action-git-status@v1
+  # swift-macos:
+  #   name: "swift (macOS)"
+  #   runs-on: macos-26
+  #   steps:
+  #     # List all environment variables to help with debugging possible issues.
+  #     - name: List environment variables
+  #       run: set
+  #     - uses: actions/checkout@v4
+  #     - name: Build package
+  #       run: swift build
+  #     - name: Build tests
+  #       run: swift build --build-tests
+  #     - name: Run tests
+  #       run: swift test --xunit-output .build/report
+  #     - name: Upload test results
+  #       if: success() || failure()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: test-macOS-swift.zip
+  #         path: .build/report-swift-testing
+  #         if-no-files-found: error
+  #     - name: Check git status
+  #       uses: Brent-Tunnicliff/action-git-status@v1
 
-  swift-linux:
-    name: "swift (Linux)"
-    runs-on: ubuntu-latest
+  swift:
+    name: "swift"
+    strategy:
+      # Don't fail the other matrix values if one fails.
+      fail-fast: false
+      matrix:
+        platform: [
+          { name: "Linux", run_on: "ubuntu-latest" },
+          { name: "macOS", run_on: "macos-latest" },
+          { name: "Windows", run_on: "windows-latest" },
+        ]
+    runs-on: ${{ matrix.platform.run_on }}
     container:
       image: swift:6.2
     steps:
@@ -161,14 +170,14 @@ jobs:
         if: success() || failure()
         uses: actions/upload-artifact@v4
         with:
-          name: test-linux-swift.zip
+          name: test-${{ matrix.platform.name }}-swift.zip
           path: .build/report-swift-testing
           if-no-files-found: error
       - name: Check git status
         uses: Brent-Tunnicliff/action-git-status@v1
 
   lint:
-    runs-on: macos-26
+    runs-on: macos-latest
     steps:
       - name: List environment variables
         run: set
